### ISSUE TITLE
Impossible to use configFile in RedisServerBuilder

### ISSUE THREAD

**Issue by 5k0rp** [codemonstur/embedded-redis#11]
Setting up the config file in RedisServerBuilder is guaranteed to throw an exception in build() because buildCommandArgs used setting("bind " + bindAddress) but any usage of setting after configFile is denied

**Comment by codemonstur** [comment]
Well that sucks. The original code was messy and hard to understand so I mostly just left it the way it was. There also weren't many example config files so I didn't have anything to test with.

Looking at it I think the code should just allow you to set a config file and set custom stuff. Then when build() is called it should create a temporary file that contains it all. It would leave it up to the user to not create invalid config files.

Do you have some config files that I can work with?

**Comment by codemonstur** [comment]
I pushed some new code to master, I think this new version will work for you. Can you test it? If you think it's alright I'll make a new release.

**Comment by codemonstur** [comment]
Tried to push a new version. But maven central isn't cooperating today. Something about them not supporting Java16 very well yet.

https://issues.sonatype.org/browse/OSSRH-66684
https://issues.sonatype.org/browse/OSSRH-66257?focusedCommentId=1036973&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1036973

**Comment by 5k0rp** [comment]
Thank you

**Comment by codemonstur** [comment]
Got tired of waiting for Maven to fix the problem. Installed Java 15 and pushed the code. It should show up soon. Maven central can sometimes be slow, max a couple of days.
