### ISSUE TITLE
Issue with missing so (eg: openssl)

### ISSUE THREAD

**Issue by 0x26res** [codemonstur/embedded-redis#18]
I'm having issue getting embedded-redis to work on docker, because of missing openssl.so.3

Steps to reproduce:

```shell
wget https://repo1.maven.org/maven2/com/github/codemonstur/embedded-redis/1.0.0/embedded-redis-1.0.0.jar
unzip embedded-redis-1.0.0.jar  -d 1.0.0
docker run -it \
  --mount type=bind,source="$(pwd)"/1.0.0,target=/app \
  --platform=linux/amd64 \
  python:3.10.13-slim-bullseye  /app/redis-server-6.2.6-v5-linux-amd64
```

Gives me:

> /app/redis-server-6.2.6-v5-linux-amd64: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

Interestingly the 32 bit version works:
```shell
docker run -it \
  --mount type=bind,source="$(pwd)"/1.0.0,target=/app \
  --platform=linux/amd64 \
  python:3.10.13-slim-bullseye  /app/redis-server-6.2.7-linux-386
```

I couldn't figure out how to install openssl3 on my docker image, so for now I've resorted to fallback to 32bit version:
```kotlin
        val map = newProvidedVersionsMap()
        map[OsArchitecture.UNIX_x86_64] = map[OsArchitecture.UNIX_x86]
        val serverBuilder = RedisServer.newRedisServer()
            .executableProvider(
                ExecutableProvider.newJarResourceProvider(map),
            )
           .build()
```

A few notes:
- there are similar issues with older version but different shared objects 
```
wget https://repo1.maven.org/maven2/com/github/codemonstur/embedded-redis/0.13.0/embedded-redis-0.13.0.jar
unzip embedded-redis-0.13.0.jar  -d 0.13.0
docker run -it \
  --mount type=bind,source="$(pwd)"/0.13.0,target=/app \
  --platform=linux/amd64 \
  python:3.10.13-slim-bullseye  /app/redis-server-2.8.19
# Works
docker run -it \
  --mount type=bind,source="$(pwd)"/0.13.0,target=/app \
  --platform=linux/amd64 \
  python:3.10.13-slim-bullseye  /app/redis-server-2.8.19-32
# Fails (missing /lib/ld-linux.so.2)
```

- Could it be because the executable isn't built with [make BUILD_TLS=yes](https://redis.io/docs/management/security/encryption/) ?
- I had a hard time debugging. It would help if the error message was printing stdout/stderr from reddit (I understand it's not easy), or at least the command arguments (that's how I managed to figure this out).

**Comment by codemonstur** [comment]
> Could it be because the executable isn't built with [make BUILD_TLS=yes](https://redis.io/docs/management/security/encryption/) ?

Quite possible. I don't know what arguments were used since I didn't build them myself. There isn't much I can do about your error in particular. If the binary doesn't work, it doesn't work. If you are lucky you can try to figure out how to include the necessary libraries in your docker image. Or you can build your own redis binary.

> I had a hard time debugging. It would help if the error message was printing stdout/stderr from reddit (I understand it's not easy), or at least the command arguments (that's how I managed to figure this out).

Yeah this is something I can probably do something about. I haven't really looked at the code but I think I should be able to add a callback handler that will notify you of any sout or serr data. Add it into the builder and only initialize it if it has been set, to stay backwards compatible.

**Comment by 0x26res** [comment]
> There isn't much I can do about your error in particular

Agreed, I actually think it would be hard to accommodate every possible architectures / set up.

**Comment by codemonstur** [comment]
I just released a new version of the lib with some minor changes to how output from the binary is monitored. It may be helpful, although I didn't really test it properly :D.

**Comment by hank-cp** [comment]
> Similar problem here. Failed to launch on Mac M2, OSX 14.1.1.
> 
> ```
> dyld[35042]: Library not loaded: /opt/homebrew/opt/openssl@3/lib/libssl.3.dylib
>   Referenced from: <65C5C8A1-8FBF-3116-9C1C-0B72A92D756E> /private/var/folders/nd/mmqz97wd537dmd_s6d6qkv580000gn/T/redis-11348387379995846249/redis-server-6.2.6-v5-darwin-arm64
>   Reason: tried: '/usr/local/mysql/lib/libssl.3.dylib' (no such file), '/libssl.3.dylib' (no such file), '/opt/homebrew/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/opt/homebrew/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/usr/lib/libssl.3.dylib' (no such file, not in dyld cache)
> ```

Solved. Rebuilding redis from source with TLS fixes the problem.

**Comment by hank-cp** [comment]
> Similar problem here. Failed to launch on Mac M2, OSX 14.1.1.
> 
> ```
> dyld[35042]: Library not loaded: /opt/homebrew/opt/openssl@3/lib/libssl.3.dylib
>   Referenced from: <65C5C8A1-8FBF-3116-9C1C-0B72A92D756E> /private/var/folders/nd/mmqz97wd537dmd_s6d6qkv580000gn/T/redis-11348387379995846249/redis-server-6.2.6-v5-darwin-arm64
>   Reason: tried: '/usr/local/mysql/lib/libssl.3.dylib' (no such file), '/libssl.3.dylib' (no such file), '/opt/homebrew/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/opt/homebrew/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/usr/lib/libssl.3.dylib' (no such file, not in dyld cache)
> ```

Solved. Rebuilding redis from source with TLS fixes the problem.

**Comment by 0x26res** [comment]
> I just released a new version of the lib with some minor changes to how output from the binary is monitored. It may be helpful, although I didn't really test it properly :D.

I gave it a try, but I don't see any difference in the output when it fails. I just get the usual:

```
                                java.io.IOException: Ready pattern not found in log. Startup log: 
                                    at redis.embedded.RedisInstance.awaitServerReady(RedisInstance.java:51)
                                    at redis.embedded.RedisInstance.start(RedisInstance.java:40)
                                    ... 152 more
```

**Comment by codemonstur** [comment]
@0x26res just pushed version 1.3.0, it has the changes that should give you stdout and stderr logging. Should be available soon on maven central.

**Comment by dream-mind** [comment]
@codemonstur  It seems to be a problem with the redis executable file. Just replace it with the latest executable file.
`Linux x64` see https://packages.redis.io/redis-stack/redis-stack-server-7.2.0-v6.jammy.x86_64.tar.gz
`Linux arm64` see https://packages.redis.io/redis-stack/redis-stack-server-7.2.0-v6.jammy.arm64.tar.gz

**Comment by codemonstur** [comment]
@dream-mind I added those binaries in a subdir so they can be used by the cached URL provider. Also ran them through virustotal just in case, although in this case it's kinda obvious that they are safe. I didn't want to replace the existing binaries since I don't know if that will break anything for existing users.

I'm closing this issue. Looks to me that it has long since been solved.
