### ISSUE TITLE
Unable to load/start Redis server with own binaries in classpath

### ISSUE THREAD

**Issue by marchpane** [codemonstur/embedded-redis#20]
Hello everyone,

I wanted to use this library with my own binaries and have placed them under `src/test/resources/` of my Maven project.

In class `ExecutableProvider` I was able to find different methods on how to load binaries. I tried `newFileThenJarResourceProvider()` and `newSystemPropertyProvider()` which loaded the files successfully.

But unfortunately when it is tried to start the server I become this error: 

https://github.com/codemonstur/embedded-redis/blob/44a9727c9958035e2b57d363853a588a88f053f2/src/main/java/redis/embedded/RedisInstance.java#L42-L44

- `java.io.IOException: Cannot run program "/***/src/test/resources/redis/binaries/macos/redis-server-6.2.6-v5-darwin-arm64" error=13, Permission denied`

I understand that this is a client issue but what I ask myself is what the purpose of the above methods than is. I'm not judging or so, just trying to understand how I could use this code with my own binaries. I assume many developers out there use machines where they cannot change the permissions of their partitions etc.

**Comment by codemonstur** [comment]
> It seems like your code currently does not allow custom locations as always the path of class `IO` is taken when calling method `getResourceAsStream("/my/custom/path")`.

It is generally a good idea to provide your own code if you are seeing a problem. Also from your screenshots I see `"redis/binaries..."` as the actual path that you are using. Which is a relative path and most likely wrong. Have you tried `"/redis/binaries..."`?

**Comment by codemonstur** [comment]
Thanks for letting me know you fixed it!
