### ISSUE TITLE
An error occurs in the docker linux environment

### ISSUE THREAD

**Issue by kimchanjung** [codemonstur/embedded-redis#21]
An error occurs in the docker linux environment. Please check.
os version
- centos7.9-openjdk-11.0.10

**Comment by codemonstur** [comment]
You are going to have to provide significantly more information if you want anything to happen. Provide your code, the error that you are seeing, and what you are trying to do.

**Comment by codemonstur** [comment]
The binary is compiled with TLS support, so it goes looking for libssl.so. It doesn't find it in the docker image so it dies with this error. You can try a different base image, install libssl in your existing image or compile your own redis binary with TLS disabled.

**Comment by Marthym** [comment]
> @Marthym The binary is compiled with TLS support, so it goes looking for libssl.so. It doesn't find it in the docker image so it dies with this error. You can try any of these:
> 
>     * a different base image,
>     * install libssl in your existing image,
>     * compile your own redis binary with TLS disabled.

With an image base on Ubuntu Jammy instead of Focal it seems OK

**Comment by codemonstur** [comment]
Sounds like you got it working.
