### ISSUE TITLE
Alternative directory for executable

### ISSUE THREAD

**Issue by robdbirch** [codemonstur/embedded-redis#24]
it is not uncommon for /tmp to be setup to deny execution of executables that reside in /tmp.

Currently within in the IO class `writeResourceToExecutableFile`
 at line 19 `File tempDirectory = Files.createDirectories(Files.createTempDirectory("redis-")).toFile();`

To specify an alternate location possibly use something like what  is below instead?

```
    /**
     * Creates a temporary directory in the given directory, or in the
     * temporary directory if dir is {@code null}.
     */
    static Path createTempDirectory(Path dir,
                                    String prefix,
                                    FileAttribute<?>[] attrs)
```

where `dir` is  either another builder param and/or env or null if neither of the others are specified?

**Comment by codemonstur** [comment]
I rewrote the code a little bit. Check the main branch to see all the changes. In short it should now be possible to write your code this way:

```
final File tempDir = fancyFactoryMethodForYourTempDir();
RedisServer redisServer = RedisServer.newRedisServer()
  .executableProvider(newJarResourceProvider(tempDir))
  .build();
```
or
```
RedisServer redisServer = RedisServer.newRedisServer()
  .executableProvider(newJarResourceProvider(YourClass::fancyFactoryMethodForYourTempDir))
  .build();
```
I haven't pushed this yet. But I like the code. If there aren't any improvements and I find no bugs I'll push it. Probably tomorrow.

**Comment by robdbirch** [comment]
I pulled, built and tested  using with and without specifying a directory  using an IOSupplier or File.

**Comment by codemonstur** [comment]
Well, life got in the way. As usual :). I just did a deploy. The new version (1.4.0) should be on maven central soon.

**Comment by robdbirch** [comment]
Awesome, thanks!
