### ISSUE TITLE
redis cluster and ipv6

### ISSUE THREAD

**Issue by kusaeva** [codemonstur/embedded-redis#25]
Hello! 
Thanks for a support of the fresh fork of very useful library!
I have a question about ipv6 support for redis cluster. README has such examplefor a bind address: 
```
String bindAddress = Inet4Address.getLocalHost().getHostAddress();
```
Was Inet4Address used intentionally because there is no support for ipv6, or am I missed something?
I have tried embedded-redis on a machine with ipv6-only
```
val bindAddress = InetAddress.getLocalHost.getHostAddress

val sentinelBuilder = RedisSentinel.newRedisSentinel().bind(bindAddress)
RedisCluster
  .newRedisCluster()
  .withSentinelBuilder(sentinelBuilder)
  .ephemeral()
  .replicationGroup("foo", 1)
```
But no success:
```
java.io.IOException: Failed to start Redis service
Cause: java.io.IOException: Ready pattern not found in log. Startup log:
```
Same code works on a machine having ipv4 bindAddress.
Any advice for me?
Thanks!

**Comment by codemonstur** [comment]
There is nothing in the code that specifically codes for either IPv4 or IPv6. It should just work. 

So first things first, add an soutListener and serrListener and get the output from the binary as it starts up. It looks like there is nothing in the standard out so I suspect there is an error lurking in the standard error stream. You can add them from the sentinel builder.

**Comment by codemonstur** [comment]
Odd.

The exception you are getting implies that the log doesn't include the startup message. Since you are starting up a sentinel the code will look for any text that matches the `.*Sentinel (runid|ID) is.*` regular expression. There definitely is such a line in the log. Fifth line down from your output is says `# Sentinel ID is cae0a33a86285c480b72f5521ff7e90e57982630`. So it should find that.

What I do notice however is that this line is somehow missing from the exception. The exception includes the whole log that it saw while starting the process. And it appears to be empty in your output.

I suggest creating an [SSCCE](http://www.sscce.org/) of your code to isolate the issue.

**Comment by kusaeva** [comment]
I think I've finally understand what is wrong.
The problem the same – I have to override redis binary to /usr/bin/redis-server because of Ubuntu version (20.04)
I successfully did it for sentinelBuilder, so we can see the logs
```
Sentinel ID is 7601da00a577dedc69fca5222a28e167f4f01f41
```
but then after buliding sentinels cluster starts to build [servers](https://github.com/codemonstur/embedded-redis/blob/master/src/main/java/redis/embedded/core/RedisClusterBuilder.java#L85)
[buildMaster](https://github.com/codemonstur/embedded-redis/blob/master/src/main/java/redis/embedded/core/RedisClusterBuilder.java#L108C19-L108C30) method calls [reset](https://github.com/codemonstur/embedded-redis/blob/master/src/main/java/redis/embedded/core/RedisServerBuilder.java#L96) which in turn resets overridden executable and provider.
Same method of RedisSentinelBuilder does not [do it](https://github.com/codemonstur/embedded-redis/blob/master/src/main/java/redis/embedded/core/RedisSentinelBuilder.java#L145)
So sentinels really started but servers are not, the line complains about servers here:
```
Ready pattern not found in log
```

Now the question is how could I override executable binary not only for sentinels but for servers of redis cluster too?

**Comment by codemonstur** [comment]
Looks like you ran into a bug with the reset function. After reading the original code from kstyrc it looks like this function was never meant to actually reset the builder. Instead it is some form of cleanup routine that clears out some temporary fields.

I've thrown out most of the code in the reset function and left only the temp values. So now the builder should retain all its settings even after a reset.

The new version of the library (1.4.2) should be available soon on maven central. Can you check if it works for you?

**Comment by kusaeva** [comment]
It works! Thank you very much for the fix!
